# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DwitBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DwitBook
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxAlamofire'
  pod 'lottie-ios'

end
